import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "category",
      label: "Khởi tạo chương trình",
      items: [
        "khởi tạo chương trình/dang_nhap_phan_mem",
        "khởi tạo chương trình/doi_mat_khau",
        "khởi tạo chương trình/cac_tien_ich_co_ban",
      ],
    },
    {
      type: "category",
      label: "Danh mục",
      items: ["danh mục/danh_muc_tai_khoan"],
    },
    // "intro",
    // "hello",
    // {
    //   type: "category",
    //   label: "Tutorial",
    //   items: ["tutorial-basics/create-a-document"],
    // },
  ],
};

export default sidebars;
